import type { Metadata } from "next"
import Link from "next/link"
import { ArrowRight, Code2, Mic2 } from "lucide-react"

export const metadata: Metadata = { title: "Text to Speech API", description: "Use the Talkata API to create speech inside your product or workflow.", alternates: { canonical: "/developer-api" } }

export default function DeveloperApiPage() {
  return <main className="min-h-screen bg-[#090910] text-white"><header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 md:px-8"><Link href="/" className="flex items-center gap-2 font-semibold"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-violet-600"><Mic2 className="h-4 w-4" /></span>Talkata</Link><Link href="/register" className="rounded-lg bg-violet-600 px-4 py-2 text-sm font-semibold hover:bg-violet-500">Create account</Link></header><section className="mx-auto max-w-6xl px-5 pb-20 pt-16 md:px-8 md:pt-24"><div className="max-w-3xl"><div className="flex items-center gap-2 text-sm font-medium text-violet-300"><Code2 className="h-4 w-4" />Developer API</div><h1 className="mt-5 text-4xl font-bold tracking-tight md:text-6xl">Speech generation for products that need an audio layer.</h1><p className="mt-6 text-base leading-7 text-white/60 md:text-lg">Create speech from text through the Talkata API. Use it in internal tools, customer products, publishing workflows, and content systems.</p><Link href="/register" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold hover:bg-violet-500">Get API access <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-14 overflow-hidden rounded-2xl border border-white/10 bg-[#11111a]"><div className="border-b border-white/10 px-5 py-3 text-xs text-white/40">POST /developer/v1/audio/speech</div><pre className="overflow-x-auto p-5 text-sm leading-7 text-violet-200">{`{ "voice_id": "your_voice_id", "text": "The text you want spoken" }`}</pre></div></section><section className="border-y border-white/10 bg-white/[.025]"><div className="mx-auto grid max-w-6xl gap-6 px-5 py-14 md:grid-cols-3 md:px-8"><Info title="Keys stay in your account" body="Create and revoke API keys from the Developer area after you sign in." /><Info title="Usage is metered" body="API usage costs $2 per 1,000,000 characters. Credits are deducted from your Talkata balance." /><Info title="Start with a small request" body="Use a short test script first. Confirm the voice and output before you move the workflow into production." /></div></section></main>
}

function Info({ title, body }: { title: string; body: string }) { return <div><h2 className="font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-white/55">{body}</p></div> }
